### ISSUE TITLE
Merging multiple SNPs into single CRISPRme Target output and disambiguating AF

### ISSUE THREAD

**Issue by dkuo-ttx** [pinellolab/CRISPRme#68] opened 2024-10-21 21:18 UTC
After running CRISPRme version 2.1.5 on spacer `sc1617.txt` (`"CTAACAGTTGCTTTTATCACNNN"`) using the tutorial provided scripts, we are observed instances where multiple SNPs are being reported for the same output site.

The command to run CRISPRme was: 
```
$ bash crisprme_auto_test_conda.sh
```
This produced this output file `sg1617.6.2.2.bestMerge.txt` and we parsed it for rows that specifically had multiple comma-delimited SNPS as follows:

```python
>>> import pandas as pd
>>> df = pd.read_csv('/path/to/Results/sg1617.6.2.2/sg1617.6.2.2.bestMerge.txt', sep='\t', low_memory=False)
>>> df[df['MMBLG_SNP'].fillna('').transform(lambda x : x.count(',') > 0)][['Chromosome','Position','MMBLG_SNP','MMBLG_AF','MMBLG_Samples','MMBLG_Reference','MMBLG_crRNA','MMBLG_DNA']].head().T
```

The resulting snippet of the DataFrame is attached as a CSV: [241021_crisprme_multisnp_example.csv](https://github.com/user-attachments/files/17466941/241021_crisprme_multisnp_example.csv)

For example, in the first entry for chr19, there are two different SNPs reported across three different samples. There is no clear link between these SNPs and samples nor is there information on the AF on a per-sample basis. 

Is the interpretation of the target match based on the composite of the SNPs used at the same time as compared to testing the SNPs individually? Could you also please elaborate on how AF is computed in this example and how is it to be interpreted relative to the three samples that are being reported?

Our question is why two different SNPs that are within a narrow proximity are being merged for the resulting site match. Our understanding is that these SNPs come from different VCF entries and ought to be evaluated individually to assess potential target match. Thanks in advance for your help.

**Comment by lindayqlin** [comment] 2024-10-22 01:44
Hello,

Thanks for using CRISPRme and for the question!

These "instances where multiple SNPs are being reported for the same output site" is an intended feature, not a bug. In these cases, we are reporting candidate off-target sites that can be introduced when multiple variants are simultaneously present in the region the guide RNA targets. 

Let's take your first column as an example:
```
Chromosome	chr19
Position	51215040
MMBLG_SNP	chr19_51215048_C_T,chr19_51215061_T_A
MMBLG_AF	0,0.36
MMBLG_Samples	HG02811,NA19026,NA19027
MMBLG_Reference	Ca-AgAaccaCcTTTgTCACAGG
MMBLG_crRNA	CTAACAGTTGCTTTTATCACNNN
MMBLG_DNA	CT-AgAaccaCcTTTATCACAGG
```
In response to your questions:
1. Yes, "the interpretation of the target match [is] based on the composite of the SNPs used at the same time."
2. AF is listed per variant in the same order, so in the example above, `chr19_51215048_C_T` has a AF of `0` in the 1000 Genomes dataset while `chr19_51215061_T_A` has a AF of `0.36`. We extract these AFs directly from the input VCF lines. We do not do any computing on/of the AFs ourselves. 
3. The CRISPRme search is haplotype-aware, so all three of the samples (`HG02811,NA19026,NA19027`) carry both variants.
4. "Two different SNPs that are within a narrow proximity are being merged for the resulting site match" because they both introduce greater homology to the guide RNA than found in the input reference genome. For instance, you can see in the alignment above (last 3 rows in the example) that at the PAM-distal end, we have a mismatched `A` in the reference genome that becomes a matched `T` when the variant is present. Similarly, at the PAM-proximal end, we have a mismatched `G` in the reference genome that becomes a matched `A` when the variant is present. (These correspond to `chr19_51215061_T_A` at the PAM-distal end and `chr19_51215048_C_T` at the PAM-proximal end -- note that this candidate off-target occurs on the (-) strand so the nucleotides are reverse complemented in the alignments shown above compared to those indicated in the variant names.)
5. Correct, "these SNPs come from different VCF entries."
6. Re: "Our understanding is that these...ought to be evaluated individually to assess potential target match" -- we do evaluate them individually as well, but we only output the candidate off-targets that meet the mismatch + bulge threshold in the search parameters. For the example above, only with both variants included does the candidate off-target fall within the specified criteria, as there are 8 mismatches between the guide RNA and the reference genome while the search specified 6 mismatches max. Our haplotype-aware search strategy ensures that although "these SNPs come from different VCF entries," the candidate off-target is biologically relevant as both variants have been observed in the same human haplotype. For a different example, if you take a look at `all_results_with_alternative_alignments.tsv` for the candidate off-target at`chr15_39435249` (your 2nd column/example), you'll see that we evaluate all sorts of combinations before outputting the one in `integrated_results.tsv`. 

By the way, I'd recommend looking at the `integrated_results.tsv` file rather than `bestMerge.txt` as the primary output from CRISPRme. The header there should hopefully be more clear, and we describe all its columns (as well as our output files in general) in [Supplementary Table 1 of our CRISPRme paper](https://static-content.springer.com/esm/art%3A10.1038%2Fs41588-022-01257-y/MediaObjects/41588_2022_1257_MOESM1_ESM.pdf).

Hope this helps! Please let us know if you have any further questions.

Sincerely,
Linda

**Comment by dkuo-ttx** [comment] 2024-10-22 23:10
Thank you @lindayqlin for the detailed reply and context! 

Is there a way to turn this feature of merging SNPS together in one call OFF?  Thanks in advance.

**Comment by lindayqlin** [comment] 2024-10-24 00:11
No problem!

No, that is not a supported use case since CRISPRme aims to nominate the candidate off-target that is the most biologically relevant and worth looking into in each genomic region.

However, a potential way to accomplish that if you wish is for sites in `integrated_results.tsv` which CRISPRme nominates with multiple variants, to look at the same coordinate in `all_results_with_alternative_alignments.tsv` and take the one(s) only containing a single variant (which will be present if it still falls within the search criteria). Alternatively, if you’re only interested in specific variants and would like to exclude others, you can consider only including variants of interest in your input to the search.

Hope this helps,
Linda

**Closed** 2024-11-04 14:51 UTC
Labels: bug
