### ISSUE TITLE
Missing Indels?  Are Indel Variants Still Supported?

### ISSUE THREAD

**Issue by tcrevier** [pinellolab/CRISPRme#59] opened 2024-05-21 20:43 UTC
I noticed that I was not getting any indels back when running the current docker against my own guides, so I ran it against the test guides and still did not get any indels.  This included indels that are in the supplemental material deposited with the original paper.

Are indels no longer supported?

**To Reproduce**

If running CRISPRme via command line, type the command line call to CRISPRme returning the error

docker run -v ${PWD}:/DATA -w /DATA -i pinellolab/crisprme crisprme.py complete-search --genome Genomes/hg38/ --vcf vcf_hg38_gnomAD.txt/ --guide sg1617.txt --pam ./PAMs/20bp-NGG-SpCas9.txt --annotation ./Annotations/encode+gencode.hg38.bed --samplesID samplesID_hg38_gnomAD.txt --gene_annotation ./Annotations/gencode.protein_coding.bed --bMax 1 --mm 4 --bDNA 1 --bRNA 1 --merge 3 --output runReference/ --thread 12

If running CRISPRme via the website, please fill the form below:
1. Spacer sequences
sg1617
CTAACAGTTGCTTTTATCACNNN

2. Cas protein

cas9

3. PAM

NGG

4. Genome

hg38

5. Variants dataset

gnomad3.1.2

7. Thresholds 
Mismatches: 4
DNA Bulges: 1
RNA Bulges:1 

**Expected behavior**
In the original paper, there is a hit at chr13, location 87474539, positive strand.  It includes the variant : chr13_87474546_AAGACCC_A which is present in the gnomad 3.1.2 dataset (https://gnomad.broadinstitute.org/variant/13-87474546-AAGACCC-A?dataset=gnomad_r3).  It matches with 4 mismatches and 1 DNA bulge.  When I manually align it, I get the same answer.  However, when I run the current docker image, I do not get this hit (and nothing close to it).  Nor do I get any indel hits, which seems highly unlikely.

I verified that the VCF has the appropriate line 

chr13	87474546	rs1168703497	AAGACCC	A	.	PASS	AF=0.00144928	GT	0/0	0/0	0/0	0/0	0/0	0/0	0/1	0/0	0/1	0/0

**Comment by ManuelTgn** [comment] 2024-05-22 15:50
Hi @tcrevier,

Thank you for bringing this to our attention.

It's unexpected that indels are not being supported and reported by CRISPRme.
Which CRISPRme's version are you running?

In the meantime, we'll investigate the issue promptly since the website is running the latest (v2.1.4).

Best regards,
Manuell

**Comment by tcrevier** [comment] 2024-05-22 17:01
I am using the currently published docker container...

**Comment by tcrevier** [comment] 2024-05-22 17:51
@ManuelTgn 
If I use the web version to do the same search, I do still see indel hits, although it does not appear to have the gnomad variants as an option.

**Comment by samuelecancellieri** [comment] 2024-05-22 17:57
Hi @tcrevier,
I've checked the docker file.
We had some problem with an intermediate version and was the default version for the docker release.
I've updated the docker file, you will need to wait few hours to see the new version of the dockerfile getting compiled.
But this hopefully will solve the problem.

Sorry for the inconvenience.

**Comment by tcrevier** [comment] 2024-05-22 18:00
@samuelecancellieri Thanks for the reply.  I am also seeing some hits for indel variants that are missed on both the web version and the docker version, should I open a separate issue for those?

**Comment by tcrevier** [comment] 2024-05-22 18:22
Sorry, typo, I meant for SNP variants.

**Comment by samuelecancellieri** [comment] 2024-05-22 21:08
Hi @tcrevier,

Yes we know that the variant process algorithm got messed up by some unexpected update of conda packages. We are trying to fix it but it's taking longer than expected.
The difference that you are noticing is in the alternative targets results or the integrated file?

Thanks.

**Comment by tcrevier** [comment] 2024-05-30 21:52
@samuelecancellieri 

A few questions :

Have you verified that the current version gives output that matches the original paper?  Are you testing the docker images before release?


Is there a reason that docker hub only latest version?  It is normal to also have  containers tagged with the version and to leave previous versions available (see for example, Crispresso2).  If you only publish the latest version and break it, I can't run anything...

**Comment by samuelecancellieri** [comment] 2024-05-30 22:12
Hi @tcrevier
We are experiencing problems with new releases of conda, causing disruption in the code.
The docker image you find on the docker hub, it's used for fat at delivery only and it's compiled starting from the dockerfile in this repo.
If you want you can download the dockerfile and change crisprme version directly to the one you want and create a local image.
Another possibility is to access, https://quay.io/repository/biocontainers/crisprme?tab=tags select a tagged version of any crisprme release and use the docker pull that comes out of the website. Does container are created when a new release comes out and are stable.

If you are encountering any error with the new releases or any results difference, I suggest you revert back to a old release that you used with no problem.

Thanks a lot.

Best,
Samuele

**Comment by tcrevier** [comment] 2024-05-30 22:27
@samuelecancellieri 

Thanks for the reply.

Is there a reason that you don't leave the old versions of the docker containers like you do with other things from the lab?  Keep in mind that since you are not tagging it with a version, there is no way to know what version it is...


Also, I would appreciate an answer that describes what testing (if any) is done before releasing a new docker container.

**Comment by samuelecancellieri** [comment] 2024-05-31 12:50
@tcrevier you are right, we can create a more release based docker containers.
we were just relaying on the quay database and the conda package management.

We usually do not specifically test docker since the docker it's just a container over the conda package, we try every time to test the conda package from release to release, but some bugs are more difficult to spot then others.
In this case, the bug arise after months due to conda migration to mamba engine, that works differently with bash error tracing and we didn't know that.

I suggest you to revert to any old release that worked fine for you since the new implementation are mainly updating or trying to clear the code with almost zero impact on results (a part from unexpected bugs obviously).

Thanks a lot for the patience.
Best,

**Comment by tcrevier** [comment] 2024-05-31 14:52
@samuelecancellieri 

Thanks, that helps me understand.  Based on what you know, what is the last version of the docker container that works?  Was it 2.1.2?  2.1.1?  It takes a long time to do a full run and compare the results, it would be helpful if you had any guidance since you know what the issue is and when it was introduced.

Thanks,
Tom

**Comment by samuelecancellieri** [comment] 2024-05-31 15:17
hi @tcrevier 

i think 2.1.1 it's a safe choice, the problem is that the bug arise recently with conda moving to mamba, so i hope older releases are ok.
maybe you can try a subset of test, like a single chromosome test.
if you have old data you can just extract a single chromosome results and then run the version of crisprme with just that chromosome to speed up the process and compare it.

thanks a lot for the patience, this conda situation caught us off guard since the main code worked fine for years and only recently we had problem with it.

best,

**Closed** 2024-11-10 12:27 UTC
Labels: bug
