### ISSUE TITLE
having issue with conda installation

### ISSUE THREAD

**Issue by snashraf** [pinellolab/CRISPRme#15] opened 2023-01-08 12:06 UTC
Dear team,

We are trying to install this software and are somehow stuck at this step.

conda create -n crisprme python=3.8 crisprme -y

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |

Could you please help in solving this ?

Regards.
Najeeb

**Comment by lucapinello** [comment] 2023-01-08 22:19
Hi Najeeb, 

Unfortunately this is a common problem of conda. My suggestion is to wait until conda resolves all the dependencies. 

Depending on your machine this may take up to 30 minutes.

Alternatively you can install first just mamba with:

`conda install mamba -y`

Then after this you can replace the conda command with mamba like this:

`mamba create -n crisprme python=3.8 crisprme -y`

Please let me know if this works for you, so I can close this.

Thanks.

**Comment by lucapinello** [comment] 2023-01-11 14:51
Hi, it seems you are trying to install crisprme with python 3.9.

Can you please send us the error you get by creating a fresh environment
with: mamba create -n crisprme *python=3.8* crisprme -y

Thanks,

Luca

**Comment by snashraf** [comment] 2023-01-12 09:02
Hi 

Now getting this error 

$ mamba create -n crisprme *python=3.8* crisprme -y
Traceback (most recent call last):
  File "/gpfs/software/genomics/CRISPRme/v2.0.9/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/gpfs/software/genomics/CRISPRme/v2.0.9/lib/python3.9/site-packages/mamba/mamba.py", line 53, in <module>
    import mamba.mamba_api as api
ImportError: /gpfs/software/genomics/CRISPRme/v2.0.9/lib/python3.9/site-packages/mamba/mamba_api.cpython-39-x86_64-linux-gnu.so: undefined symbol: archive_write_add_filter_zstd


It is the same error; Seems it is mainly related to the OS version.

**Comment by lucapinello** [comment] 2023-01-12 11:13
This problem is not relatesd to crisprme me but mamba and conda
installation. You may have a compromised base environment.

You may want to consider restarting from a fresh miniconda installation
with only mamba in the main env.

Best regards

Luca

**Comment by ManuelTgn** [comment] 2023-01-12 15:24
Hi @snashraf,

the bug you reported is actually a common issue with mamba. It can be solved by forcing conda to reinstall ```libarchive``` (the library raising the error). You can try running ```conda install libarchive --force-reinstall -yc conda-forge```. 

Once reinstalled the library you can try to reinstall CRISPRme via mamba. Let us know if this solution works for you.

For further details on the error you got from mamba, you can look at the original [issue](https://github.com/mamba-org/mamba/issues/1775) thread in the mamba repo on github.

Regards,

Manuel

**Comment by snashraf** [comment] 2023-02-02 11:04
Hi Team,

Finally !! Our IT was able to install the software.
Please let us know if we can download the reference data used in this analysis. Can you please share the location? 
Does https://www.dropbox.com/s/dl/urciozkana5md0z/crisprme_test.tar.gz contain all the reference data ( not the VCF files)?

**Comment by lindayqlin** [comment] 2023-02-05 15:12
Hi Najeeb,

That's great to hear! 

Yes, if you download that test package and run the script inside it (please see our ["Test CRISPRme"](https://github.com/pinellolab/CRISPRme#test-crisprme) instructions), you should have the reference data needed (including 1000 Genomes VCF files actually, although you're free to comment that part out if you don't want it) to launch an example search (which will automatically happen via the script unless commented out) or any search you wish.

Hope this helps and please let us know if you have any other questions!

Sincerely,
Linda

**Comment by snashraf** [comment] 2023-02-20 11:51
Dear Team,

Thanks for your fantastic work!
I was able to run and able to generate these files along with other files.

final_results_sg1617.bestMerge.txt.bestCFD.txt.CTAACAGTTGCTTTTATCACNNN  final_results_sg1617.bestMerge.txt.bestCRISTA.txt.CTAACAGTTGCTTTTATCACNNN  final_results_sg1617.bestMerge.txt.bestmmblg.txt.CTAACAGTTGCTTTTATCACNNN

Are these actual output files? Which file should I look for the final output?

It has generated another file name as log_error_no_check.txt ( Check attachment). Does it have some error logs? I would like to know if something happens at the run or if this is just a usual run.

[log_error_no_check.txt](https://github.com/pinellolab/CRISPRme/files/10784053/log_error_no_check.txt)

**Comment by ManuelTgn** [comment] 2023-02-21 15:29
Hi @snashraf ,

it looks like something weird happened while building the final reports.
Could you please report the parameters that you used during your search?

Thanks,
Manuel

**Comment by snashraf** [comment] 2023-02-21 15:45
Hi Manuel,

crisprme.py complete-search --genome Genomes/hg38/ --vcf list_vcf.txt/ --guide sg1617.txt --pam PAMs/20bp-NGG-SpCas9.txt --annotation Annotations/encode+gencode.hg38.bed --samplesID list_samplesID.txt --be-window 4,8 --be-base A --gene_annotation Annotations/gencode.protein_coding.bed --bMax 2 --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output sg1617/ --thread 8

**Comment by snashraf** [comment] 2023-02-23 15:26
Dear team,

Do you have some updates on this request?
Thanks for your kind help and support !!

Regards,
Najeeb

**Comment by ManuelTgn** [comment] 2023-02-24 14:22
Hi @snashraf,

it took sometime to reproduce the errors you reported, but it seems that removing the ending "/" in --vcf list_vcf.txt/ solves the issue. Appending "/" to the file name, made the tool interpret it as a directory, rather than a file.

The right CRISPRme final results have extensions "integrated_results" and "all_results_with_alternative_alignments".

Thanks,
Manuel

**Comment by snashraf** [comment] 2023-02-25 08:12
Hi Manuel,
I am still getting some errors. Please take a look at the attachment.
[log_error_no_check.txt](https://github.com/pinellolab/CRISPRme/files/10830559/log_error_no_check.txt)

I am running it like this. 
crisprme.py complete-search --genome Genomes/hg38/ --vcf list_vcf.txt --guide sg1617.txt --pam PAMs/20bp-NGG-SpCas9.txt --annotation Annotations/encode+gencode.hg38.bed --samplesID list_samplesID.txt --be-window 4,8 --be-base A --gene_annotation Annotations/gencode.protein_coding.bed --bMax 2 --mm 6 --bDNA 2 --bRNA 2 --merge 3 --output sg1617/ --thread 8

**Comment by snashraf** [comment] 2023-03-01 15:06
Hi Team,

I was able to generate the two files.

I have noticed that my all_results_with_alternative_alignments.tsv file has only chrM results, how ever _integrated_results.tsv file has results from chr12, chr22, chr4,ch6, chr7 amd chrM. 
Is this the correct result? 
[log_error_no_check.txt.zip](https://github.com/pinellolab/CRISPRme/files/10862402/log_error_no_check.txt.zip)

I am also attaching my log files. Please check and confirm that it finishes successfully.

**Comment by snashraf** [comment] 2023-03-08 11:42
HI team,
Did you get a chance to look into this?
Regards,
Najeeb

**Comment by ManuelTgn** [comment] 2023-04-28 18:40
Hi Najeeb,

by looking at the `log_error` file you shared it seems that CRISPRme is not correctly parsing the input VCF files. Are the input VCFs following the VCFv4.3 file format (1000 Genomes regular VCF file format)? 

If your VCF files are following gnomAD VCF file format, CRISPRme provides a utility to convert them into the 1000 Genomes format.

Manuel

**Comment by snashraf** [comment] 2023-06-25 16:38
Its ##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##hailversion=0.2.32-a5876a0a2853

Its GATK generated file. 
I have some Star alleles in the VCF file.

**Comment by snashraf** [comment] 2023-06-26 23:49
Hi Team,

I have been trying to run this tool for the last 6 months, but still, I am not able to get proper results. 
Please check the error log file. 

https://www.dropbox.com/s/pa6f3n16be110ft/log_error.txt?dl=0

**Comment by samuelecancellieri** [comment] 2023-06-27 07:23
Hello @snashraf 
I need more details on the call you are making to the software.
We need the version you are using, both CRISPRitz and CRISPRme, the input files and the complete terminal call.
Just looking at the error, seems that your VCF is not well formatted and have unexpected characters in the header or somewhere in the data.
The other error is due to unexpected symbols in the PAM sequence and in the genome.
Try to reduce the input to a minimum to reproduce the error and then send me the logs.

Thanks.

**Comment by snashraf** [comment] 2023-06-27 15:19
OK !! 
 I am using this as PAM sequence "NNNNNNNNNNNNNNNNNNNNNGG" 
Is this the correct one ?

**Comment by samuelecancellieri** [comment] 2023-06-28 09:35
That looks fine to me, maybe there is something wrong in the text file, corrupted by GitHub during the pull.
Just change the --output in --output sg1617 to make sure it's created in the correct path.

can you create a zip with the logs in the output directory please? so i can check them more easily.

best,

**Comment by snashraf** [comment] 2023-07-13 17:00
Hi Team ,

Do you have a suggestion for this problem?

Regards,
Najeeb

**Comment by samuelecancellieri** [comment] 2023-07-14 07:40
hello @snashraf 

the problem seems caused by the creation of the population distribution file, the samplesID file you provide to the software is tab separated or space separated? because the file must be tab separated.
can you attach the PopulationDistribution_* files?
so we can check if they are created correctly.

thanks,

**Closed** 2024-05-26 06:52 UTC
